### ISSUE TITLE
App Freezing/Crashing on Opening It.

### ISSUE THREAD

**Issue by cameronbosch** [flattool/warehouse#117]
- [✔️] I have read the `README.md` document
- [✔️] I am using the latest version of Warehouse
- [✔️] I am using the Flatpak package of Warehouse
- [✔️] I have not found any other opened issues on the same topic

## Describe the issue in detail
When I open Warehouse, the tool often freezes for about 20 seconds and my DE thinks the app is not responding. Occasionally, the app will just crash.

## If applicable, provide steps to reproduce the issue
1. Just open the app and give it about 5 seconds,

## Run `flatpak run io.github.flattool.Warehouse` in a terminal and if applicable, show any output
(process:2): Gtk-WARNING **: 16:56:00.450: Unknown key gtk-modules in /home/cameron/.var/app/io.github.flattool.Warehouse/config/gtk-4.0/settings.ini

### Note, this is input when the app crashes on startup
Gdk-Message: 16:56:11.513: Lost connection to Wayland compositor.

**Comment by R4csu** [comment]
If you are using explicit sync with NVIDIA latest drivers this is not a warehouse issue, used to have the same problem and that was the reason, all libadwaita apps were crashing.

https://github.com/NVIDIA/egl-wayland/issues/110#issuecomment-2132127401

**Comment by cameronbosch** [comment]
I can verify that the same issue happens on an AMD Advantage laptop (AMD CPU & AMD dGPU) today wiht the current version on Flathub. I uninstalled a Flatpak app and the same thing happened; the app froze and the terminal outputted the same message:

`Gdk-Message: 11:59:18.121: Lost connection to Wayland compositor.`

So this issue may not have been an Nvidia specific issue.

**Comment by heliguy4599** [comment]
I'm not entirely sure on the specific reason to this (I've also been unable to replicate it) but my guess is that it's due to the UI freeze that happens when adding a lot of list elements to the main view. My current approach seems to be lagging the UI thread quite a bit, which I think results in both the DE thinking the app is not responding, and whatever issue is happening with the compositor. I've looked in to better ways to approach this, and Warehouse 2.X will be much faster and less have less UI thread lag. I am sorry to say that a change like this is too much to put into Warehouse 1.X, so (what I think is) a fix to this won't be for a little bit.

**Comment by cameronbosch** [comment]
You're right. This "app not responding" situation may be a result of the large amount of flatpaks I have installed.

It's completely understandable if you can't fix it for now, given you're only one person and you haven't been able to replicate it.

I wish you luck on Warehouse 2.0!

**Comment by MajorTomDE** [comment]
Also crashing on my machine. Here the error from the command line:

```
**
Gsk:ERROR:../gsk/gpu/gskvulkanimage.c:269:gsk_vulkan_image_new: assertion failed: (width > 0 && height > 0)
Bail out! Gsk:ERROR:../gsk/gpu/gskvulkanimage.c:269:gsk_vulkan_image_new: assertion failed: (width > 0 && height > 0)
```
