### ISSUE TITLE
GUI not displayed correctly

### ISSUE THREAD

**Issue by Xathros1** [flattool/warehouse#27]
So, I've noticed after installing the flatpak version, that the GUI is not displaying correctly:
See this screenshot as an example. I'm not sure if the terminal output is related to this error.

![Screenshot_20231002_150248](https://github.com/flattool/warehouse/assets/72621668/c333cfac-12c5-41fa-a36c-6f3df034bf3e)

Sys Info:
Operating System: openSUSE Tumbleweed 20230929
KDE Plasma Version: 5.27.8
KDE Frameworks Version: 5.110.0
Qt Version: 5.15.10
Kernel Version: 6.5.4-1-default (64-bit)
Graphics Platform: Wayland
Flatpak version: Flatpak 1.15.4

**Comment by heliguy4599** [comment]
This is interesting. I am also using openSUSE Tumbleweed but I am running GNOME. I receive the same command line error which I believe is more of an issue with Tumbleweed so that cannot be it. I am unsure as to what the issue could be. I'll have to look more into how Libadwaita apps are handled on Plasma, as that is one of the major differences between your system and my system.

**Comment by AtiusAmy** [comment]
May I ask your PC specs?

**Comment by Xathros1** [comment]
ok seems like it was a kde bug that was fixed with the newest snapshot (VERSION="20231001" on TW)
