### ISSUE TITLE
Feature Request: Add app permission management on warehouse

### ISSUE THREAD

**Issue by rizalmart** [flattool/warehouse#73]
- [ ] My proposal does not exist in the `PLANNED & NOT PLANNED.md` document
- [x] I have not found any other opened issues on the same feature request
- [X] I believe this fits within Warehouse's scope of Flatpak management

## Describe the feature idea in detail
add permission management on warehouse just like flatseal. The problem with flatseal is that it has dependencies on Webkitgtk and GnomeJS. Adding flatpak app permissions on warehouse makes a great flatpak management tool.

**Comment by nekohayo** [comment]
> The problem with flatseal is that it has dependencies on Webkitgtk and GnomeJS.
I don't think dependencies is a reason enough to dismiss flatseal as a dedicated app for this task. You're not really going to be able to avoid such dependencies anyway. Email clients like Evolution and Geary, RSS readers, some browsers, GNOME Online Accounts (for now), NetworkManager and GNOME Shell itself (for captive portals) all need WebKitGTK to be installed to work.

It would make more sense for this app to call upon flatseal for managing permissions when needed, IMHO.

**Comment by heliguy4599** [comment]
Your feature request *does* exist within `PLANNED & NOT PLANNED.md`.
> Features that will never be added to Warehouse: Permission management

**Comment by c33s** [comment]
flatseal feature integration would still be awesome. why have two tools which can do half of the work when you can have one which handles all the work.

voting for reopen

**Comment by runarcn** [comment]
> flatseal feature integration would still be awesome. why have two tools which can do half of the work when you can have one which handles all the work.

Nah, do one thing and do it well. If we follow the "why have two tools" mindset, we might as well add options for browsing and installing from Flathub and other remotes, building flatpaks from source, uploading flatpaks to remotes, hell, even git version control of them. After all, why should we use several apps for handling everything flatpak-related when we can unify it in one which handles all the work?

Heli is maintaining and developing this in his free time. Making this bigger *just to make it bigger* is stupid - this isn't even about creating *new* feature and fixing unsolved problems, which is why Warehouse and Flattool were made in the first place. This suggestion will only introduce more work, more bugs, more maintenance, and make the app more bloated - I say bloated since, again, *these tools already exist*.

If you want to use flatseal, install flatseal. If you can't be assed to deal with their libraries, fork it and do a rewrite. If you can't be assed to do an entire rewrite, do the job by hand usin CLI. If neither of these are for you then idk anymore buddy, maybe you just don't care too much about those libraries anyways
